# --- RODE specific parameters ---

# use epsilon greedy action/role selector
action_selector: "soft_epsilon_greedy"
action_encoder: "obs_reward"
epsilon_start: 1.0
epsilon_finish: 0.05
role_epsilon_finish: 0.05
epsilon_anneal_time: 70000
epsilon_anneal_time_exp: 70000

runner: "episode"

buffer_size: 5000

# update the target network every {} episodes
target_update_interval: 200

# use the Q_Learner to train
agent_output_type: "q"
learner: "sr_learner"
double_q: True
mixer: "dmaq"
role_mixer: "dmaq"
mixing_embed_dim: 32
hypernet_layers: 2
hypernet_embed: 64

name: "sr_marl"
mac: "sr_mac"
agent: "sr_agent"
role: 'dot'
role_selector: 'dot'
bi_opt: False

n_role_clusters: 5
role_interval: 5
state_latent_dim: 32
action_latent_dim: 20
role_action_spaces_update_start: 50000

# qplex
adv_hypernet_layers: 3
adv_hypernet_embed: 64
num_kernel: 10
is_minus_one: True
weighted_head: True
is_adv_attention: True
is_stop_gradient: True

# for interpretability
verbose: False
